// Exported methods.
NODE_ZEPHYR_SYMBOL(sendNotice)
NODE_ZEPHYR_SYMBOL(subscribeTo)
NODE_ZEPHYR_SYMBOL(setNoticeCallback)
NODE_ZEPHYR_SYMBOL(realm)

// Keys on notice objects.
NODE_ZEPHYR_SYMBOL(version)
NODE_ZEPHYR_SYMBOL(port)
NODE_ZEPHYR_SYMBOL(checkedAuth)
NODE_ZEPHYR_SYMBOL(authentLen)
NODE_ZEPHYR_SYMBOL(asciiAuthent)
NODE_ZEPHYR_SYMBOL(class)
NODE_ZEPHYR_SYMBOL(instance)
NODE_ZEPHYR_SYMBOL(opcode)
NODE_ZEPHYR_SYMBOL(sender)
NODE_ZEPHYR_SYMBOL(recipient)
NODE_ZEPHYR_SYMBOL(format)
NODE_ZEPHYR_SYMBOL(otherFields)
NODE_ZEPHYR_SYMBOL(kind)
NODE_ZEPHYR_SYMBOL(time)
NODE_ZEPHYR_SYMBOL(auth)
NODE_ZEPHYR_SYMBOL(uid)
NODE_ZEPHYR_SYMBOL(senderAddr)
NODE_ZEPHYR_SYMBOL(body)

// ComErrException
NODE_ZEPHYR_SYMBOL(code)
